name: get likes

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 0 * * *'  # 6:00 pm IST
  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'  # Specify the Python version you need
      # Install the necessary packages
      # - name: Installed package list
      #   run: apt list --installed
      # Install dependencies
      - name: Install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt
      # Run your Python script
      - name: Run Python script
        run: python3 .py           
